[flake8]
exclude = .git, *migrations*
max-line-length = 88
select = C,E,F,W,B,B950
ignore = E203, E231, E501, W503, W291, W293

[tox]
envlist = py{310, 311, 312, 313}-django{42, 52}-esi{8}, py{310, 311, 312, 313}-django{52}-esi{9},docs, pylint

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = testsite.settings

deps =
    django42: django>=4.2,<5
    django52: django>=5.2,<6
    esi8: django-esi>=8,<9
    esi9: django-esi>=9,<10

extras =
    test

commands_pre=
    pip list

commands =
    coverage run runtests.py -v 2
    coverage xml
    coverage report

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
deps = -r{toxinidir}/docs/requirements.txt
install_command = python -I -m pip install {opts} {packages}
commands =
    sphinx-build -d "{toxworkdir}/docs_doctree" docs "{toxworkdir}/docs_out" --color -W -bhtml {posargs}

[testenv:pylint]
deps=
    pylint
    pylint-django
    django>=5.2,<6

commands=
    pylint --load-plugins pylint_django eve_auth
